"""Initial schema - all tables for ACMP

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-03-08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###

    # Tenants table
    op.create_table('tenants',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('subscription_tier', sa.String(50), nullable=False, server_default='starter'),
        sa.Column('user_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('settings', sa.String(), nullable=False, server_default='{}'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenants_created_at', 'tenants', ['created_at'])

    # Frameworks table
    op.create_table('frameworks',
        sa.Column('id', sa.String(50), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('version', sa.String(20), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('is_custom', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('tenant_id', sa.String(36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Framework versions table
    op.create_table('framework_versions',
        sa.Column('id', sa.String(50), nullable=False),
        sa.Column('framework_id', sa.String(50), nullable=False),
        sa.Column('version', sa.String(20), nullable=False),
        sa.Column('change_summary', sa.Text(), nullable=True),
        sa.Column('previous_version', sa.String(20), nullable=True),
        sa.Column('created_by', sa.String(36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_framework_versions_framework', 'framework_versions', ['framework_id'])

    # Controls table
    op.create_table('controls',
        sa.Column('id', sa.String(50), nullable=False),
        sa.Column('framework_id', sa.String(50), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(50), nullable=True),
        sa.Column('evidence_types', sa.JSON(), nullable=True),
        sa.Column('rule_type', sa.String(50), nullable=True),
        sa.Column('rule_config', sa.JSON(), nullable=True),
        sa.Column('severity', sa.String(20), nullable=False, server_default='MEDIUM'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('framework_id', 'id', name='uq_framework_control')
    )
    op.create_index('ix_controls_framework', 'controls', ['framework_id'])

    # Control results table
    op.create_table('control_results',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('control_id', sa.String(50), nullable=False),
        sa.Column('tenant_id', sa.String(36), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('evidence_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('confidence', sa.String(20), nullable=False, server_default='MEDIUM'),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('evaluated_at', sa.DateTime(), nullable=False),
        sa.Column('failing_items', sa.JSON(), nullable=True),
        sa.Column('passing_items', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_control_results_control', 'control_results', ['control_id'])
    op.create_index('ix_control_results_tenant', 'control_results', ['tenant_id'])

    # Source profiles table
    op.create_table('source_profiles',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('tenant_id', sa.String(36), nullable=False),
        sa.Column('source_type', sa.String(50), nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('scope', sa.JSON(), nullable=True),
        sa.Column('read_only', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('validated', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('last_sync', sa.DateTime(), nullable=True),
        sa.Column('sync_status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('rate_limit_config', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_profiles_tenant', 'source_profiles', ['tenant_id'])
    op.create_index('ix_source_profiles_type', 'source_profiles', ['source_type'])

    # Evidence artifacts table
    op.create_table('evidence_artifacts',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('control_id', sa.String(50), nullable=False),
        sa.Column('source_id', sa.String(36), nullable=False),
        sa.Column('tenant_id', sa.String(36), nullable=False),
        sa.Column('artifact_hash', sa.String(64), nullable=False),
        sa.Column('s3_key', sa.String(500), nullable=True),
        sa.Column('s3_bucket', sa.String(255), nullable=True, server_default='acmp-evidence'),
        sa.Column('encryption_key_id', sa.String(36), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('content_size', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('collected_at', sa.DateTime(), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_id'], ['source_profiles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('control_id', 'source_id', 'artifact_hash', name='uq_evidence_dedup')
    )
    op.create_index('ix_evidence_artifacts_hash', 'evidence_artifacts', ['artifact_hash'])
    op.create_index('ix_evidence_artifacts_collected', 'evidence_artifacts', ['collected_at'])
    op.create_index('ix_evidence_tenant_control', 'evidence_artifacts', ['tenant_id', 'control_id'])

    # Violations table
    op.create_table('violations',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('control_id', sa.String(50), nullable=False),
        sa.Column('control_result_id', sa.String(36), nullable=True),
        sa.Column('tenant_id', sa.String(36), nullable=False),
        sa.Column('severity', sa.String(20), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='OPEN'),
        sa.Column('remediation_suggestion', sa.Text(), nullable=True),
        sa.Column('opened_at', sa.DateTime(), nullable=False),
        sa.Column('closed_at', sa.DateTime(), nullable=True),
        sa.Column('closure_reason', sa.Text(), nullable=True),
        sa.Column('age_days', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('related_violation_ids', sa.JSON(), nullable=True),
        sa.Column('evidence_note', sa.Text(), nullable=True),
        sa.Column('artifact_url', sa.String(500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['control_result_id'], ['control_results.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_violations_status', 'violations', ['status'])
    op.create_index('ix_violations_opened', 'violations', ['opened_at'])
    op.create_index('ix_violations_tenant_status', 'violations', ['tenant_id', 'status'])
    op.create_index('ix_violations_severity', 'violations', ['severity'])
    op.create_index('ix_violations_control', 'violations', ['control_id'])

    # Audit logs table
    op.create_table('audit_logs',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('tenant_id', sa.String(36), nullable=False),
        sa.Column('event_type', sa.String(50), nullable=False),
        sa.Column('actor_id', sa.String(36), nullable=True),
        sa.Column('actor_type', sa.String(20), nullable=True),
        sa.Column('resource_type', sa.String(50), nullable=True),
        sa.Column('resource_id', sa.String(36), nullable=True),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('event_data', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('user_agent', sa.String(500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_tenant', 'audit_logs', ['tenant_id'])
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'])
    op.create_index('ix_audit_logs_created', 'audit_logs', ['created_at'])
    op.create_index('ix_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'])
    op.create_index('ix_audit_event_type', 'audit_logs', ['event_type'])
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    op.drop_table('audit_logs')
    op.drop_table('violations')
    op.drop_table('evidence_artifacts')
    op.drop_table('source_profiles')
    op.drop_table('control_results')
    op.drop_table('controls')
    op.drop_table('framework_versions')
    op.drop_table('frameworks')
    op.drop_table('tenants')
    
    # ### end Alembic commands ###
